resources:
  - name: S_HelmDeploy_BuildInfo_0017_resource
    type: BuildInfo
    configuration:
      sourceArtifactory: s_artifactory
      buildName: helmbuild
      buildNumber: 1
  - name: S_HelmDeploy_BuildInfo_0017_resource_git
    type: GitRepo
    configuration:
      gitProvider: gitResource
      path: ChaitanyaVootla/ymlTest
pipelines:
  - name: pipeline_S_HelmDeploy_0017
    steps:
      - name: S_HelmDeploy_0017
        type: HelmDeploy
        configuration:
          chartPath: ./myChartPath/
          helmVersion: 3
          releaseName: release
          integrations:
            - name: s_artifactory
            - name: s_kubernetes
          inputResources:
            - name: S_HelmDeploy_BuildInfo_0017_resource
            - name: S_HelmDeploy_BuildInfo_0017_resource_git
